# begin Nimble config (version 2)
when withDir(thisDir(), system.fileExists("nimble.paths")):
  include "nimble.paths"
# end Nimble config

# Cross-platform dependency resolution
# `nimble.paths` (above) is a per-machine lockfile generated by `nimble setup`.
# This repo is built from a single checkout shared by Windows and WSL/Linux
# (WSL's /mnt/d == Windows D:), so both OSes read the *same* nimble.paths --
# which only ever holds Windows absolute paths plus --noNimblePath. On Windows
# that is exactly right and the block below is skipped. On Linux those paths
# don't exist, so we re-discover the deps from this user's Nimble package dir.
#
# IMPORTANT: this must key off the *host* machine, NOT `hostOS`/`defined(windows)`
# — both of those follow the `--os` switch during cross-compilation (e.g. an
# Android build on a Windows host reports hostOS == "android"). We instead detect
# the host from an OS-set env var that `--os` can't move: Windows always exports
# OS=Windows_NT. This lets `nimble android` on Windows still find the host's deps.
import std/strutils

let hostIsWindows = getEnv("OS") == "Windows_NT" or getEnv("USERPROFILE").len > 0

proc baseName(p: string): string =
  # Last path component, separator-agnostic (avoids relying on extractFilename
  # being available in the NimScript VM).
  let i = max(p.rfind('\\'), p.rfind('/'))
  p[i + 1 .. ^1]

proc pkgVersion(dirName: string): seq[int] =
  # "naylib-26.08.0-<hash>" -> @[26, 8, 0]; the hash field is ignored.
  let parts = dirName.split('-')
  if parts.len >= 2:
    for n in parts[1].split('.'):
      try: result.add(parseInt(n))
      except ValueError: result.add(0)

proc isNewer(a, b: seq[int]): bool =
  for i in 0 ..< max(a.len, b.len):
    let av = if i < a.len: a[i] else: 0
    let bv = if i < b.len: b[i] else: 0
    if av != bv: return av > bv
  false

if not hostIsWindows:
  let pkgsDir = getEnv("HOME") & "/.nimble/pkgs2"
  if dirExists(pkgsDir):
    for dir in listDirs(pkgsDir):
      if dir.contains("/naylib-") or dir.contains("/flatty-") or
         dir.contains("/supersnappy-"):
        switch("path", dir)
  switch("path", thisDir() & "/src")
else:
  # Windows host (native or cross-compiling). nimble.paths holds absolute paths
  # hardcoded to one user's home, so a different checkout can't resolve them.
  # Re-discover from the local Nimble package dir, version-aware: several versions
  # of a dep can be installed side by side, and adding a stale one to the search
  # path could shadow the required >=26.08.0 — so pick the highest of each.
  let nimbleHome = getEnv("NIMBLE_DIR", getEnv("USERPROFILE") & "\\.nimble")
  let pkgsDir = nimbleHome & "\\pkgs2"
  if dirExists(pkgsDir):
    for pkg in ["naylib", "flatty", "supersnappy"]:
      var bestDir = ""
      var bestVer: seq[int] = @[]
      for dir in listDirs(pkgsDir):
        let base = dir.baseName
        if base.startsWith(pkg & "-"):
          let v = base.pkgVersion
          if bestDir.len == 0 or isNewer(v, bestVer):
            bestDir = dir
            bestVer = v
      if bestDir.len > 0:
        switch("path", bestDir)
  switch("path", thisDir() & "\\src")
