# begin Nimble config (version 2)
when withDir(thisDir(), system.fileExists("nimble.paths")):
  include "nimble.paths"
# end Nimble config

# Cross-platform dependency resolution
# `nimble.paths` (above) is a per-machine lockfile generated by `nimble setup`.
# This repo is built from a single checkout shared by Windows and WSL/Linux
# (WSL's /mnt/d == Windows D:), so both OSes read the *same* nimble.paths --
# which only ever holds Windows absolute paths plus --noNimblePath. On Windows
# that is exactly right and the block below is skipped. On Linux those paths
# don't exist, so we re-discover the deps from this user's Nimble package dir.
#
# raylib and its naylib bindings are not a Nimble dependency: vendor/naylib is a
# git submodule (Paycei/naylib, see its readme.md) and the game imports
# vendor/naylib/src. Its path is added after everything else because a later
# --path wins, so a naylib a stale nimble.paths still lists can never shadow it.
when not defined(windows):
  import std/strutils
  let pkgsDir = getEnv("HOME") & "/.nimble/pkgs2"
  if dirExists(pkgsDir):
    for dir in listDirs(pkgsDir):
      if dir.contains("/flatty-") or dir.contains("/supersnappy-"):
        switch("path", dir)
  switch("path", thisDir() & "/src")
  switch("path", thisDir() & "/vendor/naylib/src")

# On Windows nimble.paths normally holds correct absolute paths, so this is a
# no-op on the machine that generated it. But those paths are hardcoded to one
# user's home (e.g. C:\Users\<name>\.nimble), so a *different* Windows checkout
# can't resolve them. Re-discover from the local Nimble package dir, mirroring
# the Linux block. Unlike Linux we must be version-aware: several versions of a
# dep can be installed side by side, and adding the stale one to the search
# path could shadow the required one. So pick the highest installed version of
# each package.
when defined(windows):
  import std/strutils

  proc baseName(p: string): string =
    # Last path component, separator-agnostic (avoids relying on extractFilename
    # being available in the NimScript VM).
    let i = max(p.rfind('\\'), p.rfind('/'))
    p[i + 1 .. ^1]

  proc pkgVersion(dirName: string): seq[int] =
    # "flatty-0.3.4-<hash>" -> @[0, 3, 4]; the hash field is ignored.
    let parts = dirName.split('-')
    if parts.len >= 2:
      for n in parts[1].split('.'):
        try: result.add(parseInt(n))
        except ValueError: result.add(0)

  proc isNewer(a, b: seq[int]): bool =
    for i in 0 ..< max(a.len, b.len):
      let av = if i < a.len: a[i] else: 0
      let bv = if i < b.len: b[i] else: 0
      if av != bv: return av > bv
    false

  let nimbleHome = getEnv("NIMBLE_DIR", getEnv("USERPROFILE") & "\\.nimble")
  let pkgsDir = nimbleHome & "\\pkgs2"
  if dirExists(pkgsDir):
    for pkg in ["flatty", "supersnappy"]:
      var bestDir = ""
      var bestVer: seq[int] = @[]
      for dir in listDirs(pkgsDir):
        let base = dir.baseName
        if base.startsWith(pkg & "-"):
          let v = base.pkgVersion
          if bestDir.len == 0 or isNewer(v, bestVer):
            bestDir = dir
            bestVer = v
      if bestDir.len > 0:
        switch("path", bestDir)
  switch("path", thisDir() & "\\src")
  switch("path", thisDir() & "\\vendor\\naylib\\src")

# A clone made without --recursive has an empty vendor/naylib. Stop here: the
# compile would otherwise fail at "cannot open file: raylib" with no hint why, or
# worse, pick up an old naylib Nimble installed and fail on raylib 6 changes.
# (Nimble never reads config.nims, so `nimble install` still works.)
if not fileExists(thisDir() & "/vendor/naylib/src/raylib.nim"):
  quit "vendor/naylib is empty: run `git submodule update --init` (or clone with --recursive).", 1

# Mod models skin on the GPU (LookShader in mod_assets.nim), so raylib must
# upload the bone index/weight vertex buffers. naylib leaves that off by default.
switch("define", "NaylibSupportGpuSkinning")
