; niminst configuration file for TopHat-ShooterOS
; Run with: niminst inno TopHatShooter.ini

[Project]

Name:        "TopHatShooterOS"
DisplayName: "TopHat-ShooterOS"
Version:     "6.0.0"
Authors:     "Paycei"
Description: "TopHat-ShooterOS is a fast and chaotic bullet-heaven roguelite shooter made with Nim and Raylib."
App:         GUI
License:     "LICENSE"

[Windows]

Files: "TopHatShooterOS.exe"
Files: r"..\niminst\uninstaller.exe"
InnoSetup: "Yes"

[InnoSetup]

path         = r"c:\Program Files\Inno Setup 7\iscc.exe"
flags        = "/Q"
installerName = "TopHatShooterOS-Installer"

[C_Compiler]

path  = r""
flags = "-w"
